<?php

namespace App\Listeners;

use TightenCo\Jigsaw\Jigsaw;

/**
 * Remove collection directories that are generated by Jigsaw during build
 * but are not needed to be persisted (since their items are defined as arrays in config).
 */
class CleanupCollectionDirectories
{
    public function handle(Jigsaw $jigsaw)
    {
        $collectionsToClean = [
            'source/_redirect',
            'source/_team',
        ];

        foreach ($collectionsToClean as $dir) {
            if (is_dir($dir)) {
                $this->removeDirectory($dir);
            }
        }
    }

    /**
     * Recursively remove a directory and all its contents.
     */
    private function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        $items = scandir($dir);
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $dir . '/' . $item;
            if (is_dir($path)) {
                $this->removeDirectory($path);
            } else {
                unlink($path);
            }
        }

        rmdir($dir);
    }
}
