name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIBRESIGN_PUBLISH_FOOTER_FRAGMENTS: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer i
      - run: composer prod
      - uses: crazy-max/ghaction-github-pages@v4
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: build_production
          fqdn: libresign.coop
          jekyll: false
