name: Deploy PR previews

on: pull_request

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Set up PHP dependencie
        run: composer i
      - name: Change config.php
        run: |
          sed -i "s|libresign.coop|libresign.github.io|g" CNAME
          sed -i "s|baseUrl' => '/'|baseUrl' => 'https://LibreSign.github.io/site-preview/pr-preview/pr-${{ github.event.pull_request.number }}/'|g" config.php
          cat config.php|grep "'baseUrl' => "
          sed -i "/'matomo_container'/d" config.production.php
      - name: Run composer command
        run: composer prod

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build_production/
          pages-base-url: libresign.github.io/site-preview
          deploy-repository: LibreSign/site-preview
          preview-branch: main
          token: ${{ secrets.PREVIEW_TOKEN }}
