name: Deploy PR previews

on: pull_request

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Set up PHP dependencie
        run: composer i
      - name: Run composer command
        run: composer prod

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build_production/
