name: PR Preview Remove

on:
  pull_request_target:
    branches: [main]
    types: [closed]

permissions:
  contents: read

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
      - name: Remove preview
        uses: LibreSign/pr-preview-action@2a6da1177b47dc23173ba9a75e01da0a0d800978
        with:
          action: remove
          pr-number: ${{ github.event.pull_request.number }}
          deploy-repository: LibreSign/site-preview
          preview-branch: main
          pages-base-url: libresign.github.io/site-preview
          comment: false
          token: ${{ secrets.PREVIEW_TOKEN }}
